### ISSUE TITLE
Missing SymbolType package

### ISSUE THREAD

**Issue by lzina** [angr/angr#1608]
Hi, 
I updated angr package to latest, but now I have a problem:
```
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/fuzzer/fuzzer.py", line 4, in <module>
    import angr
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/__init__.py", line 30, in <module>
    from .sim_procedure import SimProcedure
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/sim_procedure.py", line 5, in <module>
    from cle import SymbolType
ImportError: cannot import name 'SymbolType'
```
when trying to install SymbolType in python 3.6 environment , I get the error
```
      File "/tmp/pip-install-e70a75gk/SymbolType/ez_setup/__init__.py", line 168
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
```
Except of the "Missing parentheses", how can I fix the problem of "Setuptools version",version,"or greater has been installed" which means problem with my python version. Until now, everything work well with python 3.6.

Looking forward for quick solution.
Thanks!

**Comment by rhelmot** [comment]
Symbol Type is a part of CLE, not its own package. Your angr and CLE are
out of sync - when you update part of the angr suite you need to update all
of it.
