### ISSUE TITLE
Exception raised in jump table resolver

### ISSUE THREAD

**Issue by HexRoman** [angr/angr#1090]
After upgrading to angr 7.8.6.23 from 7.8.6.16, the following code:

```
import angr
p = angr.Project(r"Crash", load_options={"auto_load_libs": False})
cfg = p.analyses.CFGFast()
```
crashes with:

```
  File "C:\python27x64ActiveState\lib\site-packages\angr\analyses\analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "C:\python27x64ActiveState\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 909, in __init__
    self._analyze()
  File "C:\python27x64ActiveState\lib\site-packages\angr\analyses\forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "C:\python27x64ActiveState\lib\site-packages\angr\analyses\forward_analysis.py", line 653, in _analysis_core_baremetal
    self._job_queue_empty()
  File "C:\python27x64ActiveState\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 1385, in _job_queue_empty
    jump_targets = list(set(self._process_indirect_jumps()))
  File "C:\python27x64ActiveState\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 2549, in _process_indirect_jumps
    resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
  File "C:\python27x64ActiveState\lib\site-packages\angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 176, in resolve
    load_addr_tmp = load_stmt.addr.tmp
AttributeError: 'Const' object has no attribute 'tmp'
```

I have manually applied the changes in the [17a43e93cf6ff9b5f9a9846a00fa53e54ed1095c commit](https://github.com/angr/angr/commit/17a43e93cf6ff9b5f9a9846a00fa53e54ed1095c#diff-a64a57e378cbee948c40d83b36d3c4aa)  but it still doesn't work. 

[puts.zip](https://github.com/angr/angr/files/2136669/puts.zip)
