### ISSUE TITLE
libafl 0.16.1 breaks the x86_64 macOS build through core_affinity2

### ISSUE THREAD

**Issue by zardus** [angr/angr#6890]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Since #6875 bumped libafl from 0.15.4 to 0.16.1, angr's Rust extension no longer compiles for x86_64 macOS. angr's own CI does not see it, because every macOS runner it uses is arm64.

Where it shows up is angr-management, whose `pyinstaller / Build on macos-15-intel` job builds angr from master. That job passed on 2026-08-15, 08-16 and 08-17 and has failed on every run since; its `Bundle` workflow on master first failed at 2026-08-18T00:13Z, about eighty minutes after #6875 merged at 2026-08-17T15:52-0700. It is currently red on angr-management#1718 and #1719 and green on every older open pull request there.

The error is in the dependency, not in angr:

```
error[E0308]: mismatched types
  --> core_affinity2-0.16.1/src/lib.rs:885:21
880 |     let result = thread_policy_get(
    |                  ----------------- arguments to this function are incorrect
885 |         &mut get_default,
    |         ^^^^^^^^^^^^^^^^ expected `*mut u32`, found `&mut bool`
```

`get_default` is declared `let mut get_default = false`, while `libc::thread_policy_get` takes `*mut boolean_t`, and `boolean_t` is `u32` on Darwin. The call sits in a `#[cfg]` branch that only compiles on x86_64 Apple targets, which is why arm64 macOS and Linux are unaffected.

Three things worth knowing before choosing a response:

- 0.16.0 and 0.16.1 contain byte-identical code at that call, so pinning to 0.16.0 does not help. 0.15.4 has no `thread_policy_get` call at all, which is why the old pin built.
- `core_affinity2` is an optional dependency of `libafl_bolts`, but it is enabled by that crate's `std` feature, so it cannot be dropped with a feature flag.
- The defect is upstream in `core_affinity2` and the fix there is a one-line cast.

That leaves reverting #6875, carrying a `[patch.crates-io]` until a fixed `core_affinity2` is released, or accepting a red Intel macOS build in the meantime — which is a call for maintainers rather than something to pick unilaterally.

Separately, this class of breakage is invisible to angr's CI: `ci.yml` uses `macos-26` and `macos-latest`, both arm64, so no job compiles the Rust extension for x86_64 Darwin. angr-management's bundle is currently the only place in the ecosystem that does.

**Comment by twizmwazin** [comment]
Make a PR patching the defect and I’ll take a look

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Happy to — one thing worth settling first, because the defect is not in this repository and the two ways to patch it are quite different.

`core_affinity2` is published from `AFLplusplus/LibAFL` (`crates/core_affinity2`), and the bug is still on their `main` today, unchanged from the released 0.16.1:

```rust
// crates/core_affinity2/src/lib.rs:874
let mut get_default = false;
...
let result = thread_policy_get(
    pthread_mach_thread_np(pthread_self()),
    THREAD_AFFINITY_POLICY as _,
    &raw mut info as thread_policy_t,
    &mut count,
    &mut get_default,   // libc wants *mut boolean_t; this is &mut bool
);
```

`libc` declares the parameter as `get_default: *mut boolean_t` (`libc-0.2.189`, `src/unix/bsd/apple/mod.rs:4626`), and `boolean_t` is `u32` on Apple. `get_default` appears only in those two lines, so it is a write-only out-parameter and the repair is one line:

```rust
let mut get_default: libc::boolean_t = 0;
```

The branch is `#[cfg]`-ed to x86_64 Apple targets, which is why arm64 macOS and Linux are unaffected and why angr's own CI never sees it — `ci.yml` uses `macos-26` and `macos-latest`, both arm64. angr-management's `pyinstaller / Build on macos-15-intel` is currently the only job in the ecosystem that compiles this code path.

So: would you rather I send that one-liner upstream to LibAFL, or make a change here — either reverting #6875 to `libafl = "=0.15.4"`, where `core_affinity2` had no `thread_policy_get` call at all, or carrying a `[patch.crates-io]` until a fixed release lands? Upstream is the real fix but leaves the build red until they cut a release; a change here unblocks immediately.

One caveat I would rather state than gloss: I cannot compile-verify either against `x86_64-apple-darwin` from this environment — no Apple target is installed and there is no rustup — so the upstream one-liner is argued from `libc`'s declaration and the compiler's own error rather than from a build I ran. An angr-side revert is testable, because angr-management's Intel macOS job is the test.
