### PR TITLE
SimCCAArch64: pass floating-point arguments the way AAPCS64 does

### PR DESCRIPTION
**Pull request by zardus**
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

### Problem

`Project.factory.callable` mispasses floating-point arguments on AArch64. For example, `sum_floats` in [`tests/aarch64/manyfloatsum`](https://github.com/angr/binaries/blob/b1e9b9cc873a2e64ccbb5345464acffb15ea3db5/tests/aarch64/manyfloatsum), called with 0 through 18, returns a symbolic value instead of `171.0`. A prototype `f(double, int, double)` is assigned `[stack+0, x0, stack+8]`.

### Root cause

`SimCCAArch64` declares no floating-point argument or return registers. The base convention therefore places floating-point arguments on the stack and reads their return values from `x0`. It also cannot assign one SIMD register to each member of a homogeneous floating-point aggregate.

### Fix

Use `v0`–`v7` for floating-point arguments and `v0` for scalar floating-point returns. Recognize homogeneous floating-point aggregates and assign one register per member. If an aggregate does not fit, place it on the stack and exhaust the floating-point register pool for subsequent arguments. Count the aggregate’s stack locations when reserving call space, including when it is the final argument, so it cannot overwrite pointer-backed data.

`f(double, int, double)` now uses `[v0, x0, v1]`, and `sum_floats` returns `171.0`. Aggregate returns, non-homogeneous aggregate arguments, and Apple's variadic convention remain outside this change.

### Testing

The regression tests check scalar and aggregate locations, register exhaustion, union classification, and calls into compiled AArch64 functions. The regression tests fail on the baseline and pass with this change. A call-state regression also checks that a final spilled aggregate does not overwrite a pointer argument’s data. Fixtures depend on angr/binaries#216, which must merge first.

Validation: https://github.com/angr/angr/pull/7036#issuecomment-5461101064

session: sharpen

### CODE REVIEW

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Calling the six sum functions in [`tests/aarch64/manyfloatsum`](https://github.com/angr/binaries/blob/b1e9b9cc873a2e64ccbb5345464acffb15ea3db5/tests/aarch64/manyfloatsum) through `Project.factory.callable`, using prototypes parsed from `tests_src/manyfloatsum.c` and arguments 0 through 18. Measured again after the rebase; warning messages and local import paths are omitted.

**Before**

<details><summary>Baseline 24737f3a28e0c7850b0ff73569598f02c2e3b473</summary>

```text
sum_floats               expected 171.0    got SYMBOLIC
sum_combo                expected 171.0    got 0
sum_segregated           expected 171.0    got 36
sum_doubles              expected 171.0    got SYMBOLIC
sum_combo_doubles        expected 171.0    got 0
sum_segregated_doubles   expected 171.0    got 0
```

</details>

**After**

<details><summary>Head e715415fe24d0e1dabc8e8a76966b3c6b894a9af</summary>

```text
sum_floats               expected 171.0    got 171.0
sum_combo                expected 171.0    got 171.0
sum_segregated           expected 171.0    got 171.0
sum_doubles              expected 171.0    got 171.0
sum_combo_doubles        expected 171.0    got 171.0
sum_segregated_doubles   expected 171.0    got 171.0
```

</details>

The calls are covered by `pytest --import-mode=append -q tests/factory/test_callable.py::TestCallable::test_manyfloatsum_aarch64`.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Validation record for head `e715415fe24d0e1dabc8e8a76966b3c6b894a9af` against baseline `24737f3a28e0c7850b0ff73569598f02c2e3b473`.

### Regression checks

From the angr worktree:

```sh
../../../../nix/run.sh --feature pr-angr-7036 -- pytest --import-mode=append -q tests/test_calling_conventions.py tests/factory/test_callable.py
```

58 tests and 16 subtests passed, exit 0. All five AArch64 regression methods detect failures on a separately built baseline: four ordinary failures and all 16 stack-allocation subcases fail (pytest reports 20 failed, 1 passed, 53 deselected).

The stack regression covers one through four float or double members, with and without a trailing scalar. It checks reserved stack space and preservation of pointer-backed data through `Project.factory.call_state`.

The six functions in `tests/aarch64/manyfloatsum` return `171.0` through `Project.factory.callable`; captured before/after results are in the [output comment](https://github.com/angr/angr/pull/7036#issuecomment-5461101023). Fixtures use binaries head `b1e9b9cc873a2e64ccbb5345464acffb15ea3db5` from the dependency linked in the body. The fixture bytes are unchanged by its rebase.

### Lint and types

```sh
nix/run.sh --feature pr-angr-7036 -- python3 -P .agents/skills/angr-validate-workspace/scripts/run-ci-diff-checks.py --repository /home/yans/angr/nonagentic/features/pr-angr-7036/repos/angr --base 24737f3a28e0c7850b0ff73569598f02c2e3b473
```

Exit 0, three changed Python files. Pylint scores: calling conventions 9.93 → 9.93; callable tests 9.48 → 9.48; calling-convention tests 9.90 → 9.92. Pyright error counts remain 5, 44, and 23 respectively. The full pre-commit hook set passes on the final tree.

### Complete gate

```sh
ANGR_TEST_JOBS=2 ./feature.sh test pr-angr-7036
```

Exit 0. Nine of fourteen suites ran and passed: workspace, test-inputs, test-packages, pre-commit, feature-build, mono, pysoot, angr, and angr-rust. The angr Python suite reported 3,100 passed, 47 skipped, 2 expected failures, and 304 passing subtests in 1,201.14 seconds. The worktree-cleanliness check passed.

Skipped suites: archinfo, pypcode, pyvex, cle, and angr-management, because those repositories are not adopted into this feature. Hosted decompiler snapshots were not run locally. The separate lint/type comparison above covers the two checks the gate does not run.

### Scope

This rebase retains the baseline's `TypeRef` handling and repairs stack-space accounting for spilled aggregates. Aggregate return values and non-homogeneous aggregate arguments remain unsupported by this convention. Inline-array and union Python-value marshalling remains a limitation of the shared serializer; location-classification checks do not establish callable support for those Python values.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

This and #7030 both add `SimCCAArch64.next_arg`, at different points in the class body, so git merges `angr/calling_conventions.py` without a conflict and the class ends up with two `next_arg` definitions. Python keeps the later one, #7030's composite-aggregate path, so this PR's homogeneous-float-aggregate path never runs and float aggregates go to x0/x1 instead of v0/v1.

Merged together on angr master:

- three of this PR's tests fail: `test_aarch64_float_args`, `test_aarch64_float_args_reach_the_callee`, `test_aarch64_homogeneous_float_aggregates`
- `pre-commit · angr` fails ruff `F811 Redefinition of unused next_arg`

Both PRs are green on their own, and master has neither method, so neither PR's CI can see this.

Whichever lands second should fold its case into the other's `next_arg` instead of adding a second one.

Evidence: the angr/mono rollup, https://github.com/angr/mono/pull/16, CI run 33273438345. The rollup now leaves #7030 out so the rest of the set can still be tested together. Same note on #7030: https://github.com/angr/angr/pull/7030#issuecomment-5467461331
