### ISSUE TITLE
Using Reassembler on a stripped binary

### ISSUE THREAD

**Issue by norrathep** [angr/angr#1139]
Hi,
I'm interested in using angr's Reassembler. So I tried it and it seems to work fine on an unstripped binary. However, when I tried with a stripped binary, it gives me a lot of errors when I compiles the re-assembly with clang:

```
/tmp/out-a70c9e.o: In function `_start':
(.text+0x0): multiple definition of `_start'
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../x86_64-linux-gnu/crt1.o:(.text+0x0): first defined here
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../x86_64-linux-gnu/crti.o: In function `_init':
(.init+0x7): undefined reference to `__gmon_start__'
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../x86_64-linux-gnu/crti.o: In function `_init':
(.init+0x11): undefined reference to `__gmon_start__'
/tmp/out-a70c9e.o: In function `sub_400460':
(.text+0x41): undefined reference to `label_2'
/tmp/out-a70c9e.o: In function `sub_400460':
(.text+0x49): undefined reference to `label_3'
/tmp/out-a70c9e.o: In function `sub_400460':
(.text+0x62): undefined reference to `label_3'
/tmp/out-a70c9e.o: In function `.label_10':
(.text+0x7a): undefined reference to `label_3'
/tmp/out-a70c9e.o: In function `.label_10':
(.text+0x82): undefined reference to `label_3'
/tmp/out-a70c9e.o: In function `.label_10':
(.text+0xa8): undefined reference to `label_3'
/tmp/out-a70c9e.o:(.text+0xb2): more undefined references to `label_3' follow
/tmp/out-a70c9e.o: In function `sub_400500':
(.text+0xd1): undefined reference to `label_7'
/tmp/out-a70c9e.o: In function `sub_400540':
(.text+0x11e): undefined reference to `label_12'
/tmp/out-a70c9e.o: In function `sub_400540':
(.text+0x126): undefined reference to `label_13'
/tmp/out-a70c9e.o: In function `sub_4003c8':
(.init+0x7): undefined reference to `label_0'
/tmp/out-a70c9e.o: In function `sub_4003c8':
(.init+0x11): undefined reference to `__gmon_start__'
```

C code that I use is a simple hello world:
`#include <stdio.h>
int main() {
    printf("Hello World\n");
}`

And it is compiled as `gcc -s hello-world.c`. 

Any idea how to fix it? I also attached the code that I used here.

Btw, I'm using angr version 7.8.2.21. Reassembler does not seem to work with the latest version (7.8.7.1).
```
File "test.py", line 5, in <module>
    ra = p.analyses.Reassembler(syntax='at&t')
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/reassembler.py", line 1667, in __init__
    self._initialize()
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/reassembler.py", line 2406, in _initialize
    data = Data(self, memory_data, section=section)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/reassembler.py", line 1161, in __init__
    self._initialize()
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/reassembler.py", line 1605, in _initialize
    content = self.binary.fast_memory_load(self.addr, self.size, str)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/reassembler.py", line 2789, in fast_memory_load
    data = self._ffi.unpack(self._ffi.cast('char*', buff), size)
  File "/home/oak/.local/lib/python2.7/site-packages/cffi/api.py", line 326, in unpack
    return self._backend.unpack(cdata, length)
TypeError: an integer is required
```

Thanks!
[out.zip](https://github.com/angr/angr/files/2215173/out.zip)

**Comment by rhelmot** [comment]
I don’t know anything about reassembler but I would bet that the crash on
the new version is a bug in a recent version of CFFI that makes it so you
can’t pass long integers into certain methods.

**Comment by norrathep** [comment]
The interesting error is this line:
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.4.0/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
```
Other lines seem to happen because Reassembler does not correctly remove all unnecessary stuff.

So I'd assume that Reassembler does not recover and assign a main symbol in the re-assembly output. I'm not familiar much with static analysis but can angr recover "main" symbol (which address should be assigned as a main label) from the executable? or can clang/gcc compile without any "main" symbol in assembly?

**Comment by ltfish** [comment]
> So I'd assume that Reassembler does not recover and assign a main symbol in the re-assembly output.

That also complies with my guess. We had heuristics for detecting the `main` function before, I think it's not working on your binary (or not working at all) for some reason. I'll debug this.
