### ISSUE TITLE
Examples not working with current version of angr

### ISSUE THREAD

**Issue by hugoreinaldo** [angr/angr#226]
A few examples at the angr-doc repo are not working with the current version of angr. The problem seems to be related to the _args_ keyword that was passed to SimState via the **kwargs. The following example illustrates the problem:

```
import angr

def main():
    proj = angr.Project('./binary', load_options={"auto_load_libs": False})

    argv = angr.claripy.BVS("arg1", 0x41 * 27)
    initial_state = proj.factory.entry_state(args=[argv])

if __name__ == '__main__':
    main()
```

The above code will throw an exception:

```
Traceback (most recent call last):
  File "unknown.py", line 10, in <module>
    main()
  File "unknown.py", line 7, in main
    initial_state = proj.factory.entry_state(args=[argv])
  File "angr/factory.py", line 218, in entry_state
    return self._project._simos.state_entry(**kwargs)
  File "angr/simos.py", line 281, in state_entry
    return self.state_blank(**kwargs)
  File "angr/simos.py", line 230, in state_blank
    state = SimState(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'args'
```

**Comment by rhelmot** [comment]
The above code works for me on linux binaries, but not windows ones. We do not support command line arguments for windows binaries yet.

Can you show me a specific example from the examples directory that fails?

**Comment by hugoreinaldo** [comment]
@rhelmot it was actually a PE file. I've cross compiled one of the examples to check the windows compatibility but as you said it seems that there is no support for command line arguments for windows binaries.

**Comment by vrthra** [comment]
The code above does not work on OSX 10.13.5 with same error.

> /usr/local/bin/python x.py
> WARNING | 2018-07-17 11:29:45,153 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
> WARNING | 2018-07-17 11:29:45,174 | cle.backends.macho | The Mach-O backend is not well-supported. Good luck!
> Traceback (most recent call last):
>   File "x.py", line 10, in <module>
>     main()
>   File "x.py", line 7, in main
>     initial_state = proj.factory.entry_state(args=[argv])
>   File "/usr/local/lib/python2.7/site-packages/angr/factory.py", line 100, in entry_state
>     return self.project.simos.state_entry(**kwargs)
>   File "/usr/local/lib/python2.7/site-packages/angr/simos/simos.py", line 181, in state_entry
>     return self.state_blank(**kwargs)
>   File "/usr/local/lib/python2.7/site-packages/angr/simos/simos.py", line 117, in state_blank
>     state = SimState(self.project, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'args'
>

**Comment by rhelmot** [comment]
Exact same story as above: angr does not understand how to provide command line arguments to macOS binaries. If you are on macOS you may still analyze windows and Linux binaries though.

**Comment by rhelmot** [comment]
(Note that since this issue was opened we gained the ability to provide command line arguments to windows binaries)
