### PR TITLE
Typehoon: name an imported struct after its layout, not another counter

### PR DESCRIPTION
**Pull request by zardus**
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Replaces the knowledge-base counter you rejected. Same defect, different naming
rule: a struct that reaches a function from elsewhere is named after its own
layout, so no counter and no decompilation order takes part in what it is
called.

### Problem

Decompile two functions of `openssh-portable/ssh-agent` (-O2 without inlining;
HuggingFace dataset `noelo-lab/decbench-dataset`, sha256
`37815b7135565c799a33ed596899589d35f8cae58eb5cc0580a161ce14bc15ec`) in one
process -- `sshkey_free` at `0x4188b0`, then `cert_free` at `0x418a80`:

```
WARNING | angr.analyses.decompiler.structured_codegen.c | Multiple definitions of struct struct_0 in function cert_free. Only the first one is emitted.
```

```c
typedef struct struct_0 {
    unsigned int field_0;
    char padding_4[4];
    long long field_8;
    ...
    long long field_a0;
} struct_0;

unsigned int cert_free(struct_0 *a0)
{
    ...
    sshbuf_free(a0->field_40);   // struct_0 declares no field_40
    sshbuf_free(a0->field_48);   // nor field_48
    free(a0->field_18);          // nor field_18
    sshkey_free(a0->field_50);   // nor field_50
    free(a0->field_58);          // nor field_58
```

The members are not missing from inference. A second, different `struct_0` was
inferred and declares exactly those; the emitted one is `sshkey_free`'s.
Whichever loses, its layout is gone from the output. Decompiling `cert_free` on
its own does not reproduce it.

### Root cause

`TypeTranslator.struct_name` numbers generated structs from a `count()` held on
the translator instance, and variable recovery builds one translator per
function, so every function calls its first generated struct `struct_0`.

The structs do not stay in the function they were inferred in. Decompiling
`sshkey_free` mints one, and `Clinic._make_function_prototype` stores it in that
function's prototype. Decompiling `cert_free`, which calls it, lifts the
callee's stored prototype at the call site --
`SimEngineVRAIL._call_add_arg_based_type_constraints` -> `type_lifter.lift` ->
`_translate_SimStruct` -> `_remember_known_struct` -- so `cert_free`'s own
translator ends up holding `known_structs["struct_0"]` pointing at
`sshkey_free`'s struct, while its own counter independently mints a different
`struct_0`. `_translate_Struct`'s early return then hands the foreign one back.

(The description this replaces blamed ground truth and said the struct never
passes through the function's own translator. Both halves were wrong, which is
why the emitter-side replacement I floated in the comments was aimed at the
wrong layer.)

Downstream, a name is assumed to identify one layout: `TypesStore` is keyed by
name, `VariableManagerInternal._register_struct_type` returns the stored
`TypeRef` when the name is taken, and `CCodeGenerator` emits one definition per
name and skips the rest.

### Fix

Re-derive a struct that arrives already carrying a generated name, and name it
after its own layout: `struct_h` followed by eight hex digits of a hash of
`type_layout_key`. That key -- name-independent and cycle-safe, and already used
by the C backend to order type definitions -- moves to `angr.utils.types` so the
translator can use it too.

* a function's own structs still come from its own counter and still start at
  `struct_0`;
* an import never draws from that counter, so what arrived from elsewhere cannot
  move the numbers a function gives its own structs;
* a layout-derived name can never equal one the counter mints.

Those three stop an import from moving a function's own numbering; the
permutation in Testing is the measurement rather than the deduction. One route
is left alone: `Typehoon` re-applies `_ground_truth` verbatim, so a user-pinned
prototype can still carry a foreign `struct_<n>` past the translator.

`cert_free` now emits both layouts and takes its own:

```c
typedef struct struct_h45844bbc { ... } struct_h45844bbc;   // sshkey_free's

typedef struct struct_0 {
    void* field_0;
    ...
    struct struct_h45844bbc *field_50;
    void* field_58;
} struct_0;

unsigned int cert_free(struct_0 *a0)
```

That struct is the same object as
`kb.functions[0x4188b0].prototype.args[0].pts_to.ty`, so renaming it in place
would change `sshkey_free`'s output too; it is re-derived from the lifted type
constants instead.

### Testing

A new test decompiles `0x412726` and then `network_host_parse_addr` at
`0x412743` in `binaries/tests/x86_64/decompiler/lighttpd`, over a scoped CFG,
and asserts that the struct type of the parameter the body reads
`a3->field_8` through declares `field_8`. It takes 8 s. On master it does not:
`a3` is `struct_0 *`, that `struct_0` declares only `field_0`, and the run logs
the warning.

Three unit tests in `tests/analyses/test_typehoon.py`: an imported name is not
kept, importing does not move this translator's own numbers, and two translators
spell the same import the same way. The first and third fail on master. One
existing test changes with the rule: `test_reverse_type_propagation` asserted
that a caller declares a variable by the callee's generated name, and now asks
for the imported name instead.

Over 2,400 functions -- six decbench objects, 400 sampled per object -- the
warning fires in 18 functions on master and 0 here, and the functions whose C
reads a member the emitted definition does not declare go from 19 to 10. 163
functions change, 82 of them only in the name of an imported struct. Decompiling
the 400 sampled functions of one object ascending and then descending changes
261 of them on master and 261 here, and on neither arm does any of the 261
differ only in a struct name; the same harness reports five such functions for
the patch this replaces.

The ten that remain are a different defect, left alone here: globals, conflated
in the process-wide `kb.variables["global"]` by `set_variable_type`, where the
first function to register `struct_0` owns that name for every later one. The
knowledge-base counter cured them only by making every name unique everywhere.
That class is
order-dependent on master today: decompiling `0x409af0` then `0x40ac30` of
decbench `findutils/find` emits `prec_table.field_0`, where the emitted
`struct_0` declares only `padding_0` and `field_10`, and the two in the other
order emit the correct `prec_table.padding_0[0]`. It deserves its own change.

Validation: https://github.com/angr/angr/pull/7122#issuecomment-5623708287

session: sharpen

### CODE REVIEW

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Superseded by the record for the current head: https://github.com/angr/angr/pull/7122#issuecomment-5623708287. What follows measured `18dbd53ff5bed39e06e8e8f6a5e1b80928b381ad`, the knowledge-base counter that was withdrawn after review, and does not describe this branch as it now stands.

**Corpus measurement.** Six decbench objects built -O2 without inlining
(`openssh-portable/scp`, `openssh-portable/sftp`, `openssh-portable/ssh-agent`,
`findutils/find`, `dpkg/dpkg`, `gnutls/certtool`), decompiled the way the
corpus sweep does -- `CFGFast(normalize=True, data_references=True)`, then
`CompleteCallingConventions(recover_variables=True)`, then the sweep's 400
sampled functions per object decompiled in one process, 2,400 functions in all.
Each arm was run twice. 15 of the 2,400 functions produce different C on two
runs of the same build; they are excluded from the change figures, and the
counts they could move are reported for both runs instead.

| | master `a34418ad568b678e66fe47ce50a9f431ab0ff801` | head `18dbd53ff` |
|---|---|---|
| functions logging "Multiple definitions of struct" | 18, 18 | 0, 0 |
| functions dereferencing a member the emitted definition does not declare | 8, 8 | 0, 0 |
| functions whose C changed | - | 704 |
| of those, identical once `struct_<n>` is normalised | - | 589 |
| substantive changes | - | 115 |
| struct definitions emitted, net over the 115 | - | +68 |
| characters, net over the 115 | - | +12,010 |
| occurrences of `->padding_\w+\[`, net over the 115 | - | +3 (12 functions fewer, 8 more) |

The padding figure counts occurrences of the regular expression `->padding_\w+\[` per function and subtracts; looser readings of "padding access" give different totals. It moves in both directions and is reported as measured. A
variable that used to be handed the other struct's layout, because
`_register_struct_type` returns the stored `TypeRef` when the name is taken, now
keeps its own, and that is sometimes the coarser of the two. On
`openssh-portable/scp`, `do_download` at `0x413b90` loses a struct-typed
parameter: `do_download(struct_0 *index, ...)` becomes
`do_download(unsigned int *index, ...)`, with `index[2]`, `index[4]` and
`index[6]` where the coarse `struct_0` gave `index->field_18` and two casts into
its padding array. The same function reads another pointer better --
`send_read_request(index, *((int *)&v58->padding_0[0]), *((long long *)&v58->padding_0[16]), *((int *)&v58->padding_0[8]), ...)`
becomes `send_read_request(index, (int)v58->field_0, v58->field_10, v58->field_8, ...)`
-- and its `->padding_` accesses go from 6 to 0. Net `goto ` over the 115 is -1,
which is inside the run-to-run noise and is not claimed as an effect.

**Local gate** (`./feature.sh test structname`, a feature collection holding
only angr, so the sibling suites did not run). Every suite and check it ran
passed; the gate's own summary line is "All selected angr workspace test suites
passed." The last row is a check the gate appends after the suite loop rather
than one of the nine selected suites.

| suite | result |
|---|---|
| angr: Python tests | 2919 passed, 47 skipped, 2 xfailed, 286 subtests passed (2080.75 s) |
| angr: Rust tests (rustylib-check derivation) | passed |
| test inputs live in angr/binaries | passed |
| a tests. import sits in a package | passed |
| all configured pre-commit hooks | passed |
| angr-agentic: workspace checks | passed |
| angr-agentic: a feature builds, tests and tears down | passed |
| angr-maintain-mono: pipeline tests | passed |
| pysoot: upstream suite | passed |
| worktree-cleanliness | passed |

The gate's environment record names the tree it built:
`features/structname/repos/angr  18dbd53ff  fix/struct-name-collision  clean`.

Suites that did **not** run, because the feature adopted only angr: archinfo,
pypcode, pyvex, cle, angr-management. A green gate that skipped a suite is green
over less than it appears to be.

**Lint and types.** Merge-base lint and pyright over the four changed files, run
by the independent reviewer through `run-ci-diff-checks.py` under the feature
env: no regression (`translator.py` pylint 8.49 to 8.50; pyright unchanged).

**Pickling.** `VariableManager` is a knowledge-base plugin and is reachable from
a pickled `Project`, so the counter is a small class rather than
`itertools.count`, which raises `TypeError` under `pickle.dumps` from Python
3.14. Measured in the feature env with warnings raised as errors:
`pickle.dumps(project)` raises no `DeprecationWarning`, the round trip restores a
working counter, and `kb.dec_variables.struct_name_ctr is
kb.variables.struct_name_ctr` both before and after it.

The class this fixes was found by a corpus sweep whose deep lanes pin angr
`a34418ad568b678e66fe47ce50a9f431ab0ff801`, the baseline above. Its per-object
counts move while it runs, so no figure from it is quoted here; the six-object
measurement in this record was taken for this branch.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Full decompilation of `cert_free` at `0x418a80` in
`openssh-portable/ssh-agent` (decbench, -O2 without inlining, sha256
`37815b7135565c799a33ed596899589d35f8cae58eb5cc0580a161ce14bc15ec`), before and
after this change. Produced by decompiling the corpus sweep's 400 sampled
functions for the object in one process, which is what the collision needs;
decompiling this function alone does not reproduce it.

**Before** — one `struct_0` is emitted, the second is dropped, and the body reads
`a0->field_18`, `a0->field_40`, `a0->field_48`, `a0->field_50` and `a0->field_58`,
none of which the emitted `struct_0` declares:

<details><summary>angr master</summary>

```c
typedef struct struct_0 {
    unsigned int field_0;
    char padding_4[4];
    long long field_8;
    long long field_10;
    char padding_18[8];
    long long field_20;
    long long field_28;
    long long field_30;
    char padding_38[40];
    void* field_60;
    char padding_68[8];
    void* field_70;
    void* field_78;
    void* field_80;
    long long field_88;
    long long field_90;
    long long field_98;
    long long field_a0;
} struct_0;

unsigned int cert_free(struct_0 *a0)
{
    unsigned int i;  // ebx
    unsigned int v2;  // ebx

    if (!a0)
    {
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        return 0;
    }
    sshbuf_free(a0->field_0);
    sshbuf_free(a0->field_40);
    sshbuf_free(a0->field_48);
    free(a0->field_18);
    if (a0->field_20)
    {
        i = 0;
        do
        {
            v2 = i + 1;
            free(*((long long *)((char *)a0->field_28 + 8 * i)));
            i = v2;
        } while (a0->field_20 > i);
    }
    free(a0->field_28);
    sshkey_free(a0->field_50);
    free(a0->field_58);
    return freezero(a0, 96);
}
```

</details>

**After** — both structs are emitted, `cert_free` takes the one it uses, and
every member it reads is declared:

<details><summary>with this change</summary>

```c
typedef struct struct_51 {
    unsigned int field_0;
    char padding_4[4];
    long long field_8;
    long long field_10;
    char padding_18[8];
    long long field_20;
    long long field_28;
    long long field_30;
    char padding_38[40];
    void* field_60;
    char padding_68[8];
    void* field_70;
    void* field_78;
    void* field_80;
    long long field_88;
    long long field_90;
    long long field_98;
    long long field_a0;
} struct_51;

typedef struct struct_52 {
    void* field_0;
    char padding_8[16];
    void* field_18;
    unsigned int field_20;
    char padding_24[4];
    void* field_28;
    char padding_30[16];
    void* field_40;
    void* field_48;
    struct struct_51 *field_50;
    void* field_58;
} struct_52;

unsigned int cert_free(struct_52 *a0)
{
    unsigned int i;  // ebx
    unsigned int v2;  // ebx

    if (!a0)
    {
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        /* unsupported instruction */
        return 0;
    }
    sshbuf_free(a0->field_0);
    sshbuf_free(a0->field_40);
    sshbuf_free(a0->field_48);
    free(a0->field_18);
    if (a0->field_20)
    {
        i = 0;
        do
        {
            v2 = i + 1;
            free(*((long long *)((char *)a0->field_28 + 8 * i)));
            i = v2;
        } while (a0->field_20 > i);
    }
    free(a0->field_28);
    sshkey_free(a0->field_50);
    free(a0->field_58);
    return freezero(a0, 96);
}
```

</details>

**Comment by ltfish** [comment]
This is a wrong fix. We should not number local structs per KB, because this will lead to different decompilation output for different function decompilation orders.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

You are right. I am taking this shape out.

I measured it rather than argue about it. Holding the semantic inputs fixed, I decompiled
`cert_free` in the `O2-noinline/openssh-portable/ssh-agent` build from the public decbench
dataset (`noelo-lab/decbench-dataset` at `4b42a0dc61`) five ways: alone; alone again in a
second process; after the 40 call-graph unrelated functions nearest it by address,
ascending; the same 40 descending; and repeated inside the same project. Those 40 are neither ancestors nor descendants of `cert_free`,
and it is the same list on every arm. The name of the struct it emits:

    arm                alone   alone (2nd proc)   after 40 asc   after 40 desc   repeat
    master 5dc307805   struct_0   struct_0         struct_0       struct_0       struct_0
    this PR's patch    struct_0   struct_0         struct_16      struct_17      struct_0

(the second row is this PR's commit cherry-picked onto that master, since the branch's own
base no longer builds here.)

So the name depends on how many unrelated functions ran first and on the order they ran
in, exactly as you said. Every difference is the name and nothing else -- normalising
`struct_<n>` makes the `after` and reversed outputs byte-identical to `alone` -- but that
is still the output moving for a reason that has nothing to do with the function. Master
does not do it.

The bug this was for is still there. Two structs minted by two different `TypeTranslator`
instances land in one function's namespace both called `struct_0`; `c.py` emits the first
and drops the second, and the body still says `struct_0`. It takes more than one function
to show up: `prec_name` at `0x40ac30` in the `O2-noinline/findutils/find` build of the same
dataset decompiles correctly on its own, but as part of a 400-function sweep of that binary
master emits

```c
typedef struct struct_0 {
    char padding_0[16];
    unsigned short field_10;
} struct_0;

extern struct_0 prec_table;
...
    iter = &prec_table.field_0;
```

where `field_0` is a member of the struct that got dropped. Across 2,400 functions from six
decbench objects, 18 on master emit the "Multiple definitions of struct" warning --
`prec_name` is not one of them, so the warning does not find every instance.

What I am trying instead is to keep the counter per translator and disambiguate where the
collision actually shows up, in the emitter: within one function's own namespace, where a
single `struct_<n>` covers two different layouts, give the later layouts the next free
number in that function. A function decompiled on its own still starts at `struct_0` and
the names depend only on which types that function holds, so it passes the table above on
every arrangement.

It is not finished, and I would rather say that than show you a number. On `prec_name` it
does spot the collision and rename -- both layouts get emitted, as `struct_0` and
`struct_1` -- but `prec_table` is still declared with one of them while the access resolves
against the other, so the declaration and the access disagree and the C is still wrong.
The patch currently on this PR gets that case right. I am also renaming during rendering in
the prototype, which is not a shape to ship -- the real form threads a per-function name
map through type rendering.

I will update this PR with the replacement rather than open another one, since the defect
and the root cause are unchanged and it is the fix shape you objected to. If you would
rather see it as a fresh pull request, say so and I will do that instead.

**Comment by ltfish** [comment]
Dear agent: Feel free to update this PR and propose a new fix.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Validation record for head `288d6ba180ce1bcd8ebf8d12f24c13c628eec0e5` against baseline `24737f3a2` (`origin/master`).

**Rebase, 2026-09-16.** This head is `680b98eceb94fa9eb631e1553dd01e671ece1bc7` replayed onto master `24737f3a2`. Two import lines conflicted with the SimTypeRef handling and vector-conversion changes that landed on master in the meantime (`c3ca0d240` and `652139216`), in `angr/analyses/decompiler/structured_codegen/c.py` and `angr/analyses/typehoon/translator.py`; the resolution kept master's imports and added `type_layout_key`, and `git range-diff` reports no other change to the commit. The corpus, reproducer and order-permutation figures below were measured on `680b98ece` against baseline `b4ad96cd3` and have **not** been re-measured on this base; they describe the same patch text on the older base. The local gate section reports the run on this head.

**Reproducer, two decompilations.** decbench `O2-noinline/openssh-portable/ssh-agent`
(HuggingFace dataset `noelo-lab/decbench-dataset`, sha256
`37815b7135565c799a33ed596899589d35f8cae58eb5cc0580a161ce14bc15ec`).
`CFGFast(normalize=True, data_references=True)`, then
`CompleteCallingConventions(recover_variables=True)`, then `0x4188b0`
(`sshkey_free`) and then `0x418a80` (`cert_free`) in one process. On the baseline
the second logs "Multiple definitions of struct struct_0 in function cert_free"
and gives `cert_free` a parameter whose struct declares none of the members the
body reads; on this head it logs nothing and emits both layouts. It is symmetric:
`cert_free` first and then `sshkey_free` also fires on the baseline.

**The same function, alone and after its callee.** Decompiled alone, `cert_free`
emits its own 11-field `struct_0` on both arms. Decompiled after `sshkey_free`,
the baseline keeps the name and puts `sshkey_free`'s 18-field layout under it. On
this head the definition differs from the alone case by exactly one line --
`void* field_50;` becomes `struct struct_h45844bbc *field_50;`, which is what the
callee's prototype actually says -- and the body is byte-identical to the alone
case once the typedefs are stripped.

**Corpus measurement.** The six decbench objects the previous record used
(`openssh-portable/scp`, `openssh-portable/sftp`, `openssh-portable/ssh-agent`,
`findutils/find`, `dpkg/dpkg`, `gnutls/certtool`), decompiled the way the corpus
sweep does, 400 sampled functions per object, 2,400 in all. Each arm was run
twice. 16 of the 2,400 functions are unstable across two runs: 11 differ between
two runs of the same baseline build and 8 differ between the head's two runs once
generated struct names are normalised (the head's second run is a rebuild), and
3 functions are in both sets. Those 16 are excluded from the change figures
below, and the counts they could move are given for both runs instead. A third
replicate found one more, so 16 is a floor; the figures hold against either
baseline run.

| | baseline `b4ad96cd3` | head |
|---|---|---|
| functions logging "Multiple definitions of struct" | 18, 18 | 0, 0 |
| functions reading a member the emitted definition does not declare | 19, 19 | 10, 10 |
| functions whose C changed | - | 163 |
| of those, identical once every generated struct name is normalised | - | 82 |
| substantive changes | - | 81 |
| struct definitions emitted, net over the 81 | - | +66 |

The ten remaining undeclared-member functions are a different defect, in
`set_variable_type`'s name-keyed branch on the process-wide
`kb.variables["global"]`, and are described in the pull request. The permutation
cited there is on `O2-noinline/findutils/find` from the same dataset, sha256
`b87890a8c8d4afee51fb254c015f9a10c6539e0eec87f1f04eaf5ffe6edb9ee4`.

One wart to record: references to a struct type that is used but never defined
go from 2 functions to 3 over the 2,400 (`findutils/find` `0x411650` gains one),
and 94 distinct `struct_h<hex>` names are emitted across the run, none of them
carrying more than one layout.

**Order permutation.** The same 400 sampled functions of
`openssh-portable/ssh-agent`, decompiled in one process in ascending address
order and, in a separate process, in descending order. Compared with no
normalisation, and then again after normalising every generated struct name:

| arm | functions differing between the two orders | of those, differing only in a struct name |
|---|---|---|
| baseline `b4ad96cd3` | 261 of 400 | 0 |
| head | 261 of 400 | 0 |
| the patch this replaces (`aeee68af7` on `5dc307805`) | 266 of 400 | 5 |

The 261 are legitimate: reversing the order changes which prototypes had been
recovered by the time each function ran. The third row is the control -- a
harness that reported 0 on every arm would be broken rather than passing -- and
it is measured on a different baseline because that patch's own base no longer
builds here.

**Local gate.** The workspace gate on this head, `./feature.sh test pr-angr-7122`. Its own ledger:

| suite | result |
|---|---|
| test-inputs, test-packages, pre-commit, feature-build, mono, pysoot | ran, passed |
| angr | ran, passed -- 3,099 passed, 47 skipped, 2 xfailed, 288 subtests, 2,270 s |
| angr-rust | ran, passed |
| workspace | ran, passed on a re-run; see below |
| archinfo, pypcode, pyvex, cle, angr-management | did NOT run: the feature has not adopted them |

9 of 14 suites ran and 5 did not, so this is green over less than the whole
ecosystem. No angr suite failed.

One suite, `workspace`, failed in the first run and its result did not stand: it
exercises this development workspace's own tooling rather than anything in angr,
and files it reads were being rewritten by unrelated processes while it ran. The
gate's own cleanliness check recorded that, reporting paths under the workspace
checkout as changed during the run but not by it. Re-run on its own it passes
(exit 0). No angr code is involved either way.

The gate runs no type checker, so angr CI's Lint and Typecheck jobs were reproduced
separately against the merge base, per changed file. No file regresses: pylint
`translator.py` 8.53 to 8.62, `utils/types.py` 9.70 to 9.73, `c.py` and the three
test files unchanged; pyright `translator.py` 11 errors to 6, every other changed
file flat.

The decompiler-snapshot comparison for the previous head classified five differing
cgc-linux64 functions, all of them the intended effect -- an imported struct taking a
layout-derived name, and members the body reads becoming declared, for instance
`i->field_0` in place of `*(&i->padding_0[0])`. No regression tell appeared in any of
them: no `goto` gained, no statement lost, no prototype lost. The comparison for this
head is read after CI republishes it.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

`cert_free` at `0x418a80` in `openssh-portable/ssh-agent` (decbench, -O2 without
inlining, sha256 `37815b7135565c799a33ed596899589d35f8cae58eb5cc0580a161ce14bc15ec`),
before and after this change. Produced by `CFGFast(normalize=True,
data_references=True)`, then `CompleteCallingConventions(recover_variables=True)`,
then two decompilations in one process: `0x4188b0` (`sshkey_free`) first, then this
one. The forty identical `/* unsupported instruction */` lines are collapsed; nothing
else is edited.


### Before

```c
typedef struct struct_0 {
    unsigned int field_0;
    char padding_4[4];
    long long field_8;
    long long field_10;
    char padding_18[8];
    long long field_20;
    long long field_28;
    long long field_30;
    char padding_38[40];
    void* field_60;
    char padding_68[8];
    void* field_70;
    void* field_78;
    void* field_80;
    long long field_88;
    long long field_90;
    long long field_98;
    long long field_a0;
} struct_0;

unsigned int cert_free(struct_0 *a0)
{
    unsigned int i;  // ebx
    unsigned int v2;  // ebx

    if (!a0)
    {
        /* unsupported instruction */ x40
        return 0;
    }
    sshbuf_free(a0->field_0);
    sshbuf_free(a0->field_40);
    sshbuf_free(a0->field_48);
    free(a0->field_18);
    if (a0->field_20)
    {
        i = 0;
        do
        {
            v2 = i + 1;
            free(*((long long *)((char *)a0->field_28 + 8 * i)));
            i = v2;
        } while (a0->field_20 > i);
    }
    free(a0->field_28);
    sshkey_free(a0->field_50);
    free(a0->field_58);
    return freezero(a0, 96);
}
```


### After

```c
typedef struct struct_h45844bbc {
    unsigned int field_0;
    char padding_4[4];
    long long field_8;
    long long field_10;
    char padding_18[8];
    long long field_20;
    long long field_28;
    long long field_30;
    char padding_38[40];
    void* field_60;
    char padding_68[8];
    void* field_70;
    void* field_78;
    void* field_80;
    long long field_88;
    long long field_90;
    long long field_98;
    long long field_a0;
} struct_h45844bbc;

typedef struct struct_0 {
    void* field_0;
    char padding_8[16];
    void* field_18;
    unsigned int field_20;
    char padding_24[4];
    void* field_28;
    char padding_30[16];
    void* field_40;
    void* field_48;
    struct struct_h45844bbc *field_50;
    void* field_58;
} struct_0;

unsigned int cert_free(struct_0 *a0)
{
    unsigned int i;  // ebx
    unsigned int v2;  // ebx

    if (!a0)
    {
        /* unsupported instruction */ x40
        return 0;
    }
    sshbuf_free(a0->field_0);
    sshbuf_free(a0->field_40);
    sshbuf_free(a0->field_48);
    free(a0->field_18);
    if (a0->field_20)
    {
        i = 0;
        do
        {
            v2 = i + 1;
            free(*((long long *)((char *)a0->field_28 + 8 * i)));
            i = v2;
        } while (a0->field_20 > i);
    }
    free(a0->field_28);
    sshkey_free(a0->field_50);
    free(a0->field_58);
    return freezero(a0, 96);
}
```

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

New fix pushed; the title and description are rewritten around it.

The counter stays on the translator. What changes is that a struct arriving
already carrying another translator's `struct_<n>` is no longer taken at face
value: it is re-derived and named after its own layout. A function's own structs
still come from its own counter and still start at `struct_0`; an import never
draws from that counter, so what arrived from elsewhere cannot move them; and a
layout-derived name can never equal one the counter mints. Those three stop an
import from moving a function's own numbering; the permutation below is the
measurement rather than the deduction. One route is left alone: `Typehoon`
re-applies `_ground_truth` verbatim after translation, so a user-pinned
prototype can still carry a foreign `struct_<n>` past the translator.

I also had the mechanism wrong in the description you read. It said the struct
arrives as ground truth and never passes through the function's own translator.
`Typehoon._ground_truth` is empty in every run that reproduces this. What
happens is that decompiling a function lifts its callees' stored prototypes at
each call site, which registers the other function's struct in this function's
own `known_structs`, and `_translate_Struct`'s early return hands it back. That
error is why the emitter-side rename I floated was aimed at the wrong layer.

The reproducer is two decompilations now instead of four hundred: `sshkey_free`
at `0x4188b0`, then `cert_free` at `0x418a80`. One existing test moves with the
rule: `test_reverse_type_propagation` asserted that a caller declares a variable
by the callee's generated struct name, which is the cross-function naming this
changes, and it now asks for the imported name.

Two measurements for the order question. First, the same function alone and
after its callee. Decompiled alone, `cert_free` emits its own 11-field
`struct_0` on both arms. Decompiled after `sshkey_free`, master keeps the name
and puts `sshkey_free`'s 18-field layout under it; here the definition differs
from the alone case by exactly one line --

```diff
-    void* field_50;
+    struct struct_h45844bbc *field_50;
```

-- which is what the callee's prototype actually says, and the body is
byte-identical to the alone case once the typedefs are stripped.

Second, the sweep's 400 sampled functions of that binary decompiled in one
process ascending, and in another process descending:

| arm | differ between the two orders | of those, differ only in a struct name |
|---|---|---|
| master `b4ad96cd3` | 261 of 400 | 0 |
| this branch | 261 of 400 | 0 |
| the patch you rejected | 266 of 400 | 5 |

The 261 are real -- reversing the order changes which prototypes had been
recovered by the time each function ran. The column that matters is the second
one, and the third row is the control: a harness reporting 0 everywhere would be
broken rather than passing.

One thing this does not fix that the rejected patch did, and I would rather say
it than let you find it. Over 2,400 corpus functions the warning goes from 18 to
0, but the functions whose C reads a member the emitted definition does not
declare only go from 19 to 10. The other ten are a different defect: globals,
conflated in the process-wide `kb.variables["global"]` by `set_variable_type`'s
name-keyed branch, where the first function to register `struct_0` owns that
name for every later one. The knowledge-base counter cured them by accident, by
making every name unique everywhere. That class is order-dependent on master
today -- decompiling `0x409af0` then `0x40ac30` of the decbench `find` build
emits `prec_table.field_0`, where the emitted `struct_0` declares only
`padding_0` and `field_10`; the two in the other order emit the correct
`prec_table.padding_0[0]`. I would rather send
that as its own change than mask it here, unless you would rather see them
together.

One knob, if you want it: 82 of 2,400 functions change only in that a struct
imported from another function is spelled by its layout where master spelled it
`struct_0`, even where nothing collides. Keeping the foreign number and falling
back to the layout name only on an actual collision would take that to zero. It
needs a name registry in the translator and a rule for two imports sharing a
name, so I left it out to keep the change small. Say the word and I will add it.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Thank you. The replacement is on this pull request now, and the per-knowledge-base counter is gone.

The rule it uses: a function's own structs still come from its own translator's counter and still start at `struct_0`. A struct that arrives already carrying another translator's generated name (through a callee's stored prototype at a call site) is re-derived and named after its own layout, `struct_h` plus eight hex digits of a hash of the layout key. That name depends on the layout and on nothing else, so it is the same in every function and in every decompilation order, and it can never equal a name the counter mints. The description explains the mechanism and the validation comment carries the measurements, including the ascending-versus-descending order permutation over 400 functions, where no function differs only in a struct name on either arm (measured against master `b4ad96cd3`, the branch's base at the time).

The branch has since been rebased onto master `24737f3a2`, where two import lines conflicted with the SimTypeRef handling and vector-conversion changes that landed on master in the meantime (`c3ca0d240` and `652139216`); the resolution kept both sides' imports and `git range-diff` reports no other change to the commit.

**Comment by zardus** [comment]
THIS MESSAGE WAS GENERATED BY AN AUTOMATED PROCESS

Closing this. `4dcd9fea9` ("TypeTranslator: Include function address in default struct names") fixes
the defect this pull request was opened for, and it fixes it in a better place than this branch did.

What the branch was for: a struct inferred while one function was being analysed reaches another
function through the callee's stored prototype. The name came from a counter held on the
`TypeTranslator` and there is one translator per function, so the caller ended up holding two
different layouts both called `struct_0`, and the C backend emitted one definition while the body
read the other one's members.

`struct_name()` now mints `st_<func_addr>_<n>` and skips any name already in `known_structs`, and
`simtype2tc` registers every lifted struct name there. That closes both halves at once: two
functions' structs cannot collide, and a name minted fresh cannot equal one that was imported.

Measured, not assumed. This branch's regression -- decompile `0x412726` and then `0x412743` in
`x86_64/decompiler/lighttpd`, and check that the typedef for the struct pointer parameter really
contains the member the body reads -- passes unmodified on master `be7190ce`, with nothing from this
branch applied. Reverting `4dcd9fea9` from that same master and running the same test again fails
it, on the defect itself:

```
WARNING  angr.analyses.decompiler.structured_codegen.c:c.py:889 Multiple definitions of struct
         struct_0 in function network_host_parse_addr. Only the first one is emitted.
AssertionError: assert 'field_8' in '\n    char field_0;'
```

So the fix is yours, and this branch has nothing left to repair.

The one piece of it that still stands is that regression. It is a working test for the defect -- it
fails on master with `4dcd9fea9` reverted, as above -- on an ELF binary rather than the Windows
sample in `test_local_struct_names.py`. It is in this branch's history at `288d6ba1` if it is ever
wanted.
