### ISSUE TITLE
Angr crashing with `AttributeError: 'Clemory' object has no attribute 'stream'`

### ISSUE THREAD

**Issue by io12** [angr/angr#1214]
```
$ uname -a
Linux thinkpad 4.14.71-1-lts #1 SMP Thu Sep 20 20:14:07 CEST 2018 x86_64 GNU/Linux
```

Distro: Arch Linux
Angr version: 7.8.2.21-1
Clemory version: 7.8.2.21-1

## Code

```
import angr

import logging
logging.getLogger('angr.sim_mananger').setLevel(logging.DEBUG)

proj = angr.Project('./sftp')
state = proj.factory.entry_state(addr=0x4013F0)
simgr = proj.factory.simgr(state)

simgr.explore(find=0x401531)

print [simgr.found[0].posix.dumps(0)]
```

## Output

```
WARNING | 2018-09-24 17:52:53,573 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
Traceback (most recent call last):
  File "verify.py", line 6, in <module>
    proj = angr.Project('./sftp')
  File "/usr/lib/python2.7/site-packages/angr/project.py", line 164, in __init__
    self.loader = cle.Loader(self.filename, **load_options)
  File "/usr/lib/python2.7/site-packages/cle/loader.py", line 126, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *force_load_libs)
  File "/usr/lib/python2.7/site-packages/cle/loader.py", line 493, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/usr/lib/python2.7/site-packages/cle/loader.py", line 587, in _load_object_isolated
    return backend_cls(full_spec, is_main_bin=self.main_object is None, loader=self, **options)
  File "/usr/lib/python2.7/site-packages/cle/backends/elf/elf.py", line 111, in __init__
    self.__register_segments()
  File "/usr/lib/python2.7/site-packages/cle/backends/elf/elf.py", line 428, in __register_segments
    self.__register_dyn(seg)
  File "/usr/lib/python2.7/site-packages/cle/backends/elf/elf.py", line 456, in __register_dyn
    self.strtab = elffile.StringTableSection(fakestrtabheader, 'strtab_cle', self.memory)
  File "/usr/lib/python2.7/site-packages/elftools/elf/sections.py", line 30, in __init__
    self.stream = self.elffile.stream
AttributeError: 'Clemory' object has no attribute 'stream'
```

Binary: [sftp.zip](https://github.com/angr/angr/files/2413056/sftp.zip)

**Comment by rhelmot** [comment]
What version of pyelftools do you have installed?

**Comment by io12** [comment]
0.25-1 apparently

**Comment by rhelmot** [comment]
okay - this is very exciting! pyelftools has finally released a new version for the first time in two years!

We currently have a compatibility shim that's meant to work with either 0.24 or 0.25, but I guess the 0.25 version broke at some point. I'll get to this in the next week. In the meantime, just install 0.24.

**Comment by io12** [comment]
Apparently the update also broke pwntools. https://github.com/Gallopsled/pwntools/issues/1189
